name          'puppet-suricata'
version       '0.1.0'
source        'https://github.com/naturalis/puppet-suricata.git'
author        'Paul Gomersbach'
license       'Apache 2.0'
summary       'suricata installation'
description   ''
project_page  'https://github.com/naturalis/puppet-suricata'

dependency 'puppetlabs/stdlib'
